### PR TITLE
Remove the --unsorted flag which needed/supported anymore. The use of…

### PR DESCRIPTION
**Pull request by jojohans**
… this flag prevented the walk-states command from working.

### CODE REVIEW

**Comment by martin-volf** [comment]
This is my mistake. `--unsorted` should stay, but not in this form - I proposed this flag to be added to upstream DrNED, but they asked it to be changed to the "positive" form, i.e. `--ordered=false` (with `--ordered` taking `true` by default). I did this and it is already part of both upstream DrNED as well as our builtin DrNED (see commit 4800c44), but I forgot to change the name in XMNR code using this - can you change your patch to do that?

**Comment by jojohans** [comment]
Done! See what you think now.

**Comment by martin-volf** [comment]
Thanks, that's what I had in mind. Btw., how did you find it? I'm not using `walk-states` often; the lux test would reveal that I assume, but obviously I do not run it regularly.

**Comment by jojohans** [comment]
I just happened to try walk-states a while ago and noticed that it didn't work. Then I met with the IOS-XR test team last week and they also mentioned that they had tried walk-states so I decided to figure out what was wrong.

**Pull request merged**
